apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: test
spec:
  selector:
    matchLabels:
      app: app2
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: app2
        tier: backend
        track: stable
    spec:
      containers:
        - name: app2
          image: soloveiruslan1989/app2
          resources:
            requests:
              memory: "100Mi"
          ports:
            - name: http
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: app2
  namespace: test
spec:
  selector:
    app: app2
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
