apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: test
spec:
  selector:
    matchLabels:
      app: app1
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: app1
        tier: backend
        track: stable
    spec:
      containers:
        - name: app1
          image: soloveiruslan1989/app1
          resources:
            requests:
              memory: "100Mi"
          ports:
            - name: http
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: app1
  namespace: test
spec:
  selector:
    app: app1
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
